
CREATE TABLE questions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  question TEXT,
  opt1 TEXT,
  opt2 TEXT,
  opt3 TEXT,
  correct INTEGER,
  location_id INTEGER,
  location_name TEXT,
  question_type_id INTEGER,
  question_type_name TEXT,
  level INTEGER,
  score INTEGER
);


INSERT INTO questions (question, opt1, opt2, opt3, correct, location_id, location_name, question_type_id, question_type_name, level, score) VALUES ('What is the largest desert in Africa?', 'Kalahari', 'Sahara', 'Namib', 2, 2, 'Africa', 2, 'science', 1, 100);
INSERT INTO questions (question, opt1, opt2, opt3, correct, location_id, location_name, question_type_id, question_type_name, level, score) VALUES ('What animal is known for jumping and carrying babies?', 'Kangaroo', 'Koala', 'Emu', 1, 6, 'Australia', 4, 'nature', 1, 100);
INSERT INTO questions (question, opt1, opt2, opt3, correct, location_id, location_name, question_type_id, question_type_name, level, score) VALUES ('What animal is known for jumping and carrying babies?', 'Kangaroo', 'Koala', 'Emu', 1, 6, 'Australia', 4, 'nature', 1, 100);
INSERT INTO questions (question, opt1, opt2, opt3, correct, location_id, location_name, question_type_id, question_type_name, level, score) VALUES ('What is the capital of Canada?', 'Vancouver', 'Ottawa', 'Montreal', 2, 4, 'North America', 1, 'geography', 1, 100);
INSERT INTO questions (question, opt1, opt2, opt3, correct, location_id, location_name, question_type_id, question_type_name, level, score) VALUES ('Which country is known for Mount Fuji?', 'China', 'Japan', 'India', 2, 3, 'Asia', 1, 'geography', 1, 100);
INSERT INTO questions (question, opt1, opt2, opt3, correct, location_id, location_name, question_type_id, question_type_name, level, score) VALUES ('Which animal is known as the king of the jungle?', 'Lion', 'Elephant', 'Tiger', 1, 2, 'Africa', 4, 'nature', 1, 100);
INSERT INTO questions (question, opt1, opt2, opt3, correct, location_id, location_name, question_type_id, question_type_name, level, score) VALUES ('Which animal has a long neck?', 'Elephant', 'Crocodile', 'Giraffe', 3, 2, 'Africa', 4, 'nature', 1, 100);
INSERT INTO questions (question, opt1, opt2, opt3, correct, location_id, location_name, question_type_id, question_type_name, level, score) VALUES ('In which country is the Colosseum located?', 'France', 'Spain', 'Italy', 3, 1, 'Europe', 3, 'culture', 1, 100);
INSERT INTO questions (question, opt1, opt2, opt3, correct, location_id, location_name, question_type_id, question_type_name, level, score) VALUES ('Which flightless bird lives in Australia?', 'Penguin', 'Emu', 'Ostrich', 2, 6, 'Australia', 4, 'nature', 1, 100);
INSERT INTO questions (question, opt1, opt2, opt3, correct, location_id, location_name, question_type_id, question_type_name, level, score) VALUES ('Which river flows through the Amazon rainforest?', 'Amazon', 'Nile', 'Yangtze', 1, 5, 'South America', 2, 'science', 1, 100);
INSERT INTO questions (question, opt1, opt2, opt3, correct, location_id, location_name, question_type_id, question_type_name, level, score) VALUES ('Which animal has a long neck?', 'Elephant', 'Crocodile', 'Giraffe', 3, 2, 'Africa', 4, 'nature', 1, 100);
INSERT INTO questions (question, opt1, opt2, opt3, correct, location_id, location_name, question_type_id, question_type_name, level, score) VALUES ('In which country is Machu Picchu?', 'Brazil', 'Peru', 'Colombia', 2, 5, 'South America', 5, 'history', 1, 100);
INSERT INTO questions (question, opt1, opt2, opt3, correct, location_id, location_name, question_type_id, question_type_name, level, score) VALUES ('What is the name of the coral reef in Australia?', 'Great Reef', 'Blue Reef', 'Great Barrier Reef', 3, 6, 'Australia', 2, 'science', 1, 100);
INSERT INTO questions (question, opt1, opt2, opt3, correct, location_id, location_name, question_type_id, question_type_name, level, score) VALUES ('What animal is known for jumping and carrying babies?', 'Kangaroo', 'Koala', 'Emu', 1, 6, 'Australia', 4, 'nature', 1, 100);
INSERT INTO questions (question, opt1, opt2, opt3, correct, location_id, location_name, question_type_id, question_type_name, level, score) VALUES ('Which waterfall is between USA and Canada?', 'Niagara', 'Victoria', 'Angel', 1, 4, 'North America', 2, 'science', 1, 100);
INSERT INTO questions (question, opt1, opt2, opt3, correct, location_id, location_name, question_type_id, question_type_name, level, score) VALUES ('What is the name of the coral reef in Australia?', 'Great Reef', 'Blue Reef', 'Great Barrier Reef', 3, 6, 'Australia', 2, 'science', 1, 100);
INSERT INTO questions (question, opt1, opt2, opt3, correct, location_id, location_name, question_type_id, question_type_name, level, score) VALUES ('Which waterfall is between USA and Canada?', 'Niagara', 'Victoria', 'Angel', 1, 4, 'North America', 2, 'science', 1, 100);
INSERT INTO questions (question, opt1, opt2, opt3, correct, location_id, location_name, question_type_id, question_type_name, level, score) VALUES ('What covers most of Antarctica?', 'Sand', 'Ice', 'Forest', 2, 7, 'Antarctica', 2, 'science', 1, 100);
INSERT INTO questions (question, opt1, opt2, opt3, correct, location_id, location_name, question_type_id, question_type_name, level, score) VALUES ('Which river flows through the Amazon rainforest?', 'Amazon', 'Nile', 'Yangtze', 1, 5, 'South America', 2, 'science', 1, 100);
INSERT INTO questions (question, opt1, opt2, opt3, correct, location_id, location_name, question_type_id, question_type_name, level, score) VALUES ('What is the capital of France?', 'Paris', 'Rome', 'Berlin', 1, 1, 'Europe', 1, 'geography', 1, 100);
INSERT INTO questions (question, opt1, opt2, opt3, correct, location_id, location_name, question_type_id, question_type_name, level, score) VALUES ('In which country is the Colosseum located?', 'France', 'Spain', 'Italy', 3, 1, 'Europe', 3, 'culture', 1, 100);
INSERT INTO questions (question, opt1, opt2, opt3, correct, location_id, location_name, question_type_id, question_type_name, level, score) VALUES ('What animal is known for jumping and carrying babies?', 'Kangaroo', 'Koala', 'Emu', 1, 6, 'Australia', 4, 'nature', 1, 100);
INSERT INTO questions (question, opt1, opt2, opt3, correct, location_id, location_name, question_type_id, question_type_name, level, score) VALUES ('Which animal lives in Antarctica?', 'Penguin', 'Polar bear', 'Camel', 1, 7, 'Antarctica', 4, 'nature', 1, 100);
INSERT INTO questions (question, opt1, opt2, opt3, correct, location_id, location_name, question_type_id, question_type_name, level, score) VALUES ('Which animal has a long neck?', 'Elephant', 'Crocodile', 'Giraffe', 3, 2, 'Africa', 4, 'nature', 1, 100);
INSERT INTO questions (question, opt1, opt2, opt3, correct, location_id, location_name, question_type_id, question_type_name, level, score) VALUES ('Which animal is known as the king of the jungle?', 'Lion', 'Elephant', 'Tiger', 1, 2, 'Africa', 4, 'nature', 1, 100);
INSERT INTO questions (question, opt1, opt2, opt3, correct, location_id, location_name, question_type_id, question_type_name, level, score) VALUES ('In which country is Machu Picchu?', 'Brazil', 'Peru', 'Colombia', 2, 5, 'South America', 5, 'history', 1, 100);
INSERT INTO questions (question, opt1, opt2, opt3, correct, location_id, location_name, question_type_id, question_type_name, level, score) VALUES ('Which river flows through the Amazon rainforest?', 'Amazon', 'Nile', 'Yangtze', 1, 5, 'South America', 2, 'science', 1, 100);
INSERT INTO questions (question, opt1, opt2, opt3, correct, location_id, location_name, question_type_id, question_type_name, level, score) VALUES ('Where is the Great Wall located?', 'India', 'Japan', 'China', 3, 3, 'Asia', 1, 'geography', 1, 100);
INSERT INTO questions (question, opt1, opt2, opt3, correct, location_id, location_name, question_type_id, question_type_name, level, score) VALUES ('What is sushi made of?', 'Rice and fish', 'Bread and cheese', 'Beef and noodles', 1, 3, 'Asia', 3, 'culture', 1, 100);
INSERT INTO questions (question, opt1, opt2, opt3, correct, location_id, location_name, question_type_id, question_type_name, level, score) VALUES ('What is the name of the coral reef in Australia?', 'Great Reef', 'Blue Reef', 'Great Barrier Reef', 3, 6, 'Australia', 2, 'science', 1, 100);
INSERT INTO questions (question, opt1, opt2, opt3, correct, location_id, location_name, question_type_id, question_type_name, level, score) VALUES ('What covers most of Antarctica?', 'Sand', 'Ice', 'Forest', 2, 7, 'Antarctica', 2, 'science', 1, 100);
INSERT INTO questions (question, opt1, opt2, opt3, correct, location_id, location_name, question_type_id, question_type_name, level, score) VALUES ('Where is the Great Wall located?', 'India', 'Japan', 'China', 3, 3, 'Asia', 1, 'geography', 1, 100);
INSERT INTO questions (question, opt1, opt2, opt3, correct, location_id, location_name, question_type_id, question_type_name, level, score) VALUES ('Which city is known for the Statue of Liberty?', 'Toronto', 'New York', 'Los Angeles', 2, 4, 'North America', 1, 'geography', 1, 100);
INSERT INTO questions (question, opt1, opt2, opt3, correct, location_id, location_name, question_type_id, question_type_name, level, score) VALUES ('What is the climate in Antarctica?', 'Hot', 'Mild', 'Cold', 3, 7, 'Antarctica', 2, 'science', 1, 100);
INSERT INTO questions (question, opt1, opt2, opt3, correct, location_id, location_name, question_type_id, question_type_name, level, score) VALUES ('Which country is known for Mount Fuji?', 'China', 'Japan', 'India', 2, 3, 'Asia', 1, 'geography', 1, 100);
INSERT INTO questions (question, opt1, opt2, opt3, correct, location_id, location_name, question_type_id, question_type_name, level, score) VALUES ('Which animal lives in Antarctica?', 'Penguin', 'Polar bear', 'Camel', 1, 7, 'Antarctica', 4, 'nature', 1, 100);
INSERT INTO questions (question, opt1, opt2, opt3, correct, location_id, location_name, question_type_id, question_type_name, level, score) VALUES ('What is the largest desert in Africa?', 'Kalahari', 'Sahara', 'Namib', 2, 2, 'Africa', 2, 'science', 1, 100);
INSERT INTO questions (question, opt1, opt2, opt3, correct, location_id, location_name, question_type_id, question_type_name, level, score) VALUES ('Where is the Great Wall located?', 'India', 'Japan', 'China', 3, 3, 'Asia', 1, 'geography', 1, 100);
INSERT INTO questions (question, opt1, opt2, opt3, correct, location_id, location_name, question_type_id, question_type_name, level, score) VALUES ('Which waterfall is between USA and Canada?', 'Niagara', 'Victoria', 'Angel', 1, 4, 'North America', 2, 'science', 1, 100);
INSERT INTO questions (question, opt1, opt2, opt3, correct, location_id, location_name, question_type_id, question_type_name, level, score) VALUES ('Which animal is known as the king of the jungle?', 'Lion', 'Elephant', 'Tiger', 1, 2, 'Africa', 4, 'nature', 1, 100);
INSERT INTO questions (question, opt1, opt2, opt3, correct, location_id, location_name, question_type_id, question_type_name, level, score) VALUES ('What is the climate in Antarctica?', 'Hot', 'Mild', 'Cold', 3, 7, 'Antarctica', 2, 'science', 1, 100);
INSERT INTO questions (question, opt1, opt2, opt3, correct, location_id, location_name, question_type_id, question_type_name, level, score) VALUES ('Which dance originated in Argentina?', 'Samba', 'Tango', 'Flamenco', 2, 5, 'South America', 3, 'culture', 1, 100);
INSERT INTO questions (question, opt1, opt2, opt3, correct, location_id, location_name, question_type_id, question_type_name, level, score) VALUES ('Which flightless bird lives in Australia?', 'Penguin', 'Emu', 'Ostrich', 2, 6, 'Australia', 4, 'nature', 1, 100);
INSERT INTO questions (question, opt1, opt2, opt3, correct, location_id, location_name, question_type_id, question_type_name, level, score) VALUES ('Which dance originated in Argentina?', 'Samba', 'Tango', 'Flamenco', 2, 5, 'South America', 3, 'culture', 1, 100);
INSERT INTO questions (question, opt1, opt2, opt3, correct, location_id, location_name, question_type_id, question_type_name, level, score) VALUES ('Which city is known for the Statue of Liberty?', 'Toronto', 'New York', 'Los Angeles', 2, 4, 'North America', 1, 'geography', 1, 100);
INSERT INTO questions (question, opt1, opt2, opt3, correct, location_id, location_name, question_type_id, question_type_name, level, score) VALUES ('In which country is Machu Picchu?', 'Brazil', 'Peru', 'Colombia', 2, 5, 'South America', 5, 'history', 1, 100);
INSERT INTO questions (question, opt1, opt2, opt3, correct, location_id, location_name, question_type_id, question_type_name, level, score) VALUES ('Which dance originated in Argentina?', 'Samba', 'Tango', 'Flamenco', 2, 5, 'South America', 3, 'culture', 1, 100);
INSERT INTO questions (question, opt1, opt2, opt3, correct, location_id, location_name, question_type_id, question_type_name, level, score) VALUES ('What covers most of Antarctica?', 'Sand', 'Ice', 'Forest', 2, 7, 'Antarctica', 2, 'science', 1, 100);
INSERT INTO questions (question, opt1, opt2, opt3, correct, location_id, location_name, question_type_id, question_type_name, level, score) VALUES ('What covers most of Antarctica?', 'Sand', 'Ice', 'Forest', 2, 7, 'Antarctica', 2, 'science', 1, 100);
INSERT INTO questions (question, opt1, opt2, opt3, correct, location_id, location_name, question_type_id, question_type_name, level, score) VALUES ('Which country is known for Mount Fuji?', 'China', 'Japan', 'India', 2, 3, 'Asia', 1, 'geography', 1, 100);